In [4]:
# import libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [7]:
# read dataset
iris_df = pd.read_csv('iris_data.csv')
iris_df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [8]:
#scaling
from sklearn.preprocessing import StandardScaler

In [15]:
scaler = StandardScaler()

In [16]:
scaler.fit(iris_df.drop('species',axis=1))

StandardScaler(copy=True, with_mean=True, with_std=True)

In [17]:
scaled_features = scaler.transform(iris_df.drop('species',axis=1))

In [19]:
iris_scaled = pd.DataFrame(data=scaled_features,columns=iris_df.columns[:-1])

In [20]:
iris_scaled.head()

sepal_length  sepal_width  petal_length  petal_width
0     -0.900681     1.032057     -1.341272    -1.312977
1     -1.143017    -0.124958     -1.341272    -1.312977
2     -1.385353     0.337848     -1.398138    -1.312977
3     -1.506521     0.106445     -1.284407    -1.312977
4     -1.021849     1.263460     -1.341272    -1.312977

In [21]:
#splitting data

In [22]:
from sklearn.model_selection import train_test_split

In [40]:
X = iris_scaled
y = iris_df['species']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3)

In [41]:
#training data

In [42]:
from sklearn.neighbors import KNeighborsClassifier

In [105]:
knn = KNeighborsClassifier(n_neighbors=39)

In [106]:
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=39, p=2,
                     weights='uniform')

In [107]:
prediction = knn.predict(X_test)

In [108]:
#evaluation 
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,prediction))
print(classification_report(y_test,prediction))

[[16  0  0]
 [ 0 13  1]
 [ 0  4 11]]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        16
  versicolor       0.76      0.93      0.84        14
   virginica       0.92      0.73      0.81        15

    accuracy                           0.89        45
   macro avg       0.89      0.89      0.88        45
weighted avg       0.90      0.89      0.89        45



In [67]:
# attempting to find best k

In [100]:
lowest_error = 1
best_k = None

for i in range(1,100):
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(X_train,y_train)
    prediction = knn.predict(X_test)
    error = np.mean(prediction != y_test)
    if error < lowest_error:
        lowest_error = error
        best_k = i
        
print(lowest_error)
print(best_k)

0.044444444444444446
1


In [103]:
# retrain with new k
knn = KNeighborsClassifier(n_neighbors=best_k)
knn.fit(X_train,y_train)
prediction = knn.predict(X_test)

In [104]:
# reevaluation
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,prediction))
print('\n')
print(classification_report(y_test,prediction))

[[16  0  0]
 [ 0 14  0]
 [ 0  2 13]]


              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        16
  versicolor       0.88      1.00      0.93        14
   virginica       1.00      0.87      0.93        15

    accuracy                           0.96        45
   macro avg       0.96      0.96      0.95        45
weighted avg       0.96      0.96      0.96        45

